### PR TITLE
Change ITALICS to BOLD in help function

### PR DESCRIPTION
**Pull request by marcosvafg**

### CODE REVIEW

**Comment by danishprakash** [comment]
@marcosvafg the changes needed were just to remove the italics formatting. Adding bold was unnecessary. However, thanks for the PR, you may look into issue #4  which is quite similar to this.

Also, always refer to the issue number by `Fixes #[issue number]`, this makes it easier for someone else looking at the issue to know that someone has already made a PR for the issue.  Also, providing a brief description about the PR would help everyone reading the PR understand the issue and the fix.

Good Luck!

**Comment by marcosvafg** [comment]
I made changes for Issue #2 and #4 but I don´'t know if I send it correctly

**Comment by prakashdanish** [comment]
@marcosvafg remove changes for #1 from in your fork and leave changes that you have made for #4  and then do a rebase, the conflict would be resolved. Let me know if you need any help.

**Review by danishprakash — CHANGES_REQUESTED** [review]
@marcosvafg remove changes for #1 from in your fork and leave changes that you have made for #4 and then do a rebase, the conflict would be resolved. Let me know if you need any help.

**Review by danishprakash — COMMENTED** [review]
yes, this looks good. Just squash all your commits into one and It'll be good to go.

**Comment by danishprakash** [comment]
@marcosvafg are you working on this?

**Comment by marcosvafg** [comment]
@prakashdanish unfortunately not. I tried to do a rebase, like you sad, but my limitated Git knowledge made it impossible. Sorry for that!

**Review by danishprakash — CHANGES_REQUESTED** [review]
@marcosvafg that's no problem, just follow this simple tutorial that explains how to squash commits [here](https://blog.ona.io/general/2016/02/02/squashing-with-git-interactive-rebase.html). Ping me if you need any help or feel stuck somewhere 😄

**Review by danishprakash — COMMENTED** [review]
@marcosvafg are you working on this PR? Let me know if not and I'll close this so that someone else could take it up.

**Comment by marcosvafg** [comment]
Sorry @prakashdanish I'm not working on this due to lack of time. You can close it if you want.

**Pull request closed without merging**
